using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace AlenMotorsDAL {
    internal static class UserManagerGeneric {
        /// <summary>
        /// Encodes the password(string) using SHA-1 Encryption algorithm with additional 64base string(Generated from salt) for added security 
        /// </summary>
        /// <param name="password">Provide the password</param>
        /// <param name="salt">Proved the salt. An additinal encryption parameter</param>
        /// <returns></returns>
        public static string EncodePassword(string password, string salt) {
            // Generate a Base64 string
            byte[] saltBytes = Encoding.UTF8.GetBytes(salt);
            string base64 = Convert.ToBase64String(saltBytes);
            // A small addition to the regular SHA1 encryption for added security
            byte[] passBytes = Encoding.Unicode.GetBytes(password);
            byte[] src = Convert.FromBase64String(base64);
            byte[] dst = new byte[src.Length + passBytes.Length];
            Buffer.BlockCopy(src, 0, dst, 0, src.Length);
            Buffer.BlockCopy(passBytes, 0, dst, src.Length, passBytes.Length);
            // Encrypt the generated Bytes using SHA-1 Algorithm
            HashAlgorithm hashAlgorithm = HashAlgorithm.Create("SHA1");
            byte[] inArray = hashAlgorithm.ComputeHash(dst);
            return Convert.ToBase64String(inArray);
        }
    }
}