//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlenMotorsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int VehicleID { get; set; }
        public int LicensePlate { get; set; }
        public string Manufacturer { get; set; }
        public int ManufacturYear { get; set; }
        public string Model { get; set; }
        public int DistanceTraveled { get; set; }
        public string Transmission { get; set; }
        public string Status { get; set; }
        public string Color { get; set; }
        public string ImageUrl { get; set; }
        public int BranchID { get; set; }
        public int Price { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
